//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DG.BotWorld.WorldMatrix.WinApp.UserControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RunnerUserControlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RunnerUserControlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DG.BotWorld.WorldMatrix.WinApp.UserControls.Resources.RunnerUserControlResource", typeof(RunnerUserControlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string AndText {
            get {
                return ResourceManager.GetString("AndText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot &apos;{0}&apos; has finished environment..
        /// </summary>
        internal static string BotHasFinishedMessage {
            get {
                return ResourceManager.GetString("BotHasFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot &apos;{0}&apos; is thinking. Wait....
        /// </summary>
        internal static string BotIsThinkingMessage {
            get {
                return ResourceManager.GetString("BotIsThinkingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots &apos;{0}&apos; are thinking. Wait....
        /// </summary>
        internal static string BotsAreThinkingMessage {
            get {
                return ResourceManager.GetString("BotsAreThinkingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots &apos;{0}&apos; have finished environment..
        /// </summary>
        internal static string BotsHaveFinishedMessage {
            get {
                return ResourceManager.GetString("BotsHaveFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment finished in {0} cycles.
        /// </summary>
        internal static string EnvironmentFinishedInCyclesMessage {
            get {
                return ResourceManager.GetString("EnvironmentFinishedInCyclesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment initialized.
        /// </summary>
        internal static string EnvironmentInitializedMessage {
            get {
                return ResourceManager.GetString("EnvironmentInitializedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment stopped.
        /// </summary>
        internal static string EnvironmentStoppedMessage {
            get {
                return ResourceManager.GetString("EnvironmentStoppedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment runner.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment runner - {0}  cycles.
        /// </summary>
        internal static string TitleWithCycles {
            get {
                return ResourceManager.GetString("TitleWithCycles", resourceCulture);
            }
        }
    }
}
